language: node_js
node_js:
  - "node"
deploy:
  provider: surge
  skip_cleanup: true
notifications:
  slack: 
    rooms:
      - uvudevclub:HthyoiZ5Igmcf4WdttRG6Gcb#builds_and_deploys
    on_success: always
